### ISSUE TITLE
Implement post-build actions by adding an after-steps 

### ISSUE THREAD

**Issue by seanly** [opsbox-dev/oes-jenkins-library#1]
Implement post-build completion actions

```yaml
variables:
  DOCKER_REG: registry.cn-chengdu.aliyuncs.com

secrets:
  DOCKER_AUTH: usernamePassword/docker-auth

steps:
  - name: docker login
    use: script
    run: |
      echo -n "${DOCKER_AUTH_PSW}" | docker login -u ${DOCKER_AUTH_USR} --password-stdin ${DOCKER_REG}
  
  - name: build
    image: rockylinux:8
    use: script
    run: |
      echo "docker build image..."
      docker build -t ${DOCKER_REG}/k8ops/test .
      docker push ${DOCKER_REG}/k8ops/test

after-steps:

  - name: docker logout
    use: script
    run: |
      docker logout ${DOCKER_REG}
```
