### ISSUE TITLE
add archiveArtifacts step

### ISSUE THREAD

**Issue by seanly** [opsbox-dev/oes-jenkins-library#7]
https://www.jenkins.io/doc/pipeline/steps/core/#archiveartifacts-archive-the-artifacts

```yaml

stages:
- name: archive
  steps:
    - use: archiveArtifacts
      with: 
        artifacts: "**/*.tar.gz"
        allowEmptyArchive: false
        
```
